"""Pytest directory-specific hook implementations"""
import os

import pytest
from pandas import to_datetime  # type: ignore
from sqlalchemy import create_engine  # type: ignore
from sqlalchemy.orm import Session  # type: ignore

from trafficstat.crash_data_ingester import CrashDataReader
from trafficstat.crash_data_schema import Base as CDBase, Crash, CrashDiagram, PdfReport, Roadway
from trafficstat.ms2generator_schema import Base as Ms2Base, CircumstanceSanitized, CitationCodeSanitized, \
    CrashSanitized, EmsSanitized, PersonSanitized, RoadwaySanitized, TrailerSanitized, VehicleSanitized


@pytest.fixture(name='crash_data_reader')
def crash_data_reader_fixture(tmpdir):
    """Fixture for the CrashDataReader class"""
    yield CrashDataReader(conn_str='sqlite:///{}'.format(os.path.join(tmpdir, 'crashdatareaderfixture.db')))


@pytest.fixture(name='conn_str_sanitized')
def unsanitized_crash_database(tmpdir):
    """Fixture for the WorksheetMaker class"""
    conn_str = 'sqlite:///{}'.format(os.path.join(tmpdir, 'crashdatabase.db'))

    # Make the database
    engine = create_engine(conn_str, echo=True, future=True)

    with engine.begin() as connection:
        Ms2Base.metadata.create_all(connection)

    with Session(bind=engine) as session:
        session.add_all([
            # acrs_crashes_sanitized
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='11.04', COLLISION_TYPE_CODE='01', SURF_COND_CODE='02', LANE_CODE='N1',
                           RD_COND_CODE='01', FIX_OBJ_CODE='00', REPORT_NO='A0000001', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'), ACC_TIME='0900', LOC_CODE='622',
                           RAMP_FLAG='N',
                           SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None, AGENCY_CODE='AD', AREA_CODE='UNK',
                           HARM_EVENT_CODE1='02', HARM_EVENT_CODE2='02', LOC_CASE_NO='153J11191',
                           ACRS_REPORT_NO='A0000001', REPORT_TYPE_CODE='03', LANE_NUMBER=1,
                           LANE_DIRECTION_CODE='01', LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='02',
                           TRAFFIC_CONTROL_CODE='01', TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=1,
                           INTER_AREA_CODE='01', SCHOOL_BUS_INVOLVED_CODE='01', C_M_LOCATION_CODE='A9.99',
                           C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='VEHICLE 2 WAS PARKED AND UNOCCUPIED IN THE REAR OF 4300 E. MONUMENT ST.  ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='99',
                           COLLISION_TYPE_CODE='99', SURF_COND_CODE='A9.99', LANE_CODE='U9', RD_COND_CODE='A9.99',
                           FIX_OBJ_CODE='00', REPORT_NO='A0000002', WEATHER_CODE='00',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'), ACC_TIME='1630', LOC_CODE='CAD1815',
                           RAMP_FLAG='N',
                           SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None, AGENCY_CODE='AD', AREA_CODE='UNK',
                           HARM_EVENT_CODE1='02', HARM_EVENT_CODE2='00', LOC_CASE_NO='159J11405',
                           ACRS_REPORT_NO='A0000002', REPORT_TYPE_CODE='03', LANE_NUMBER=0,
                           LANE_DIRECTION_CODE='99', LANE_TYPE_CODE='99', INTERSECTION_TYPE_CODE='99',
                           TRAFFIC_CONTROL_CODE='01', TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=0,
                           INTER_AREA_CODE='99', SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='ON 10/26/15 AT APPROXIMATELY1600 HOURS VEHICLE 2 WAS LEFT PARKED AND . ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='03', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='01',
                           COLLISION_TYPE_CODE='17', SURF_COND_CODE='02', LANE_CODE='S2', RD_COND_CODE='01',
                           FIX_OBJ_CODE='08', REPORT_NO='A0000003', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'), ACC_TIME='2220',
                           LOC_CODE='CAD2902', RAMP_FLAG='N', SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='09', HARM_EVENT_CODE2='10',
                           LOC_CASE_NO='154J11543',
                           ACRS_REPORT_NO='A0000003', REPORT_TYPE_CODE='03', LANE_NUMBER=2,
                           LANE_DIRECTION_CODE='02',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00', TRAFFIC_CONTROL_CODE='01',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=4, INTER_AREA_CODE='02',
                           SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='V1 WAS TRAVELING SOUTH BOUND ON 5800 BELAIR RD. DRIVER OF V1 FELL A SLEEP  ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='03', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='01',
                           COLLISION_TYPE_CODE='03', SURF_COND_CODE='02', LANE_CODE='S1', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00',
                           REPORT_NO='A0000004', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'),
                           ACC_TIME='2030',
                           LOC_CODE='CAD#2638', RAMP_FLAG='N', SIGNAL_FLAG='Y', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='01', HARM_EVENT_CODE2='01',
                           LOC_CASE_NO='155J11494',
                           ACRS_REPORT_NO='A0000004', REPORT_TYPE_CODE='03', LANE_NUMBER=1,
                           LANE_DIRECTION_CODE='02',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00', TRAFFIC_CONTROL_CODE='03',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='Y', NUM_LANES=2, INTER_AREA_CODE='00',
                           SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='THE NORTHERN DISTRICT 5 CENTRAL COMPLAINT NUMBER IS 155J11494 (5-151011494),',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='00',
                           COLLISION_TYPE_CODE='03', SURF_COND_CODE='02', LANE_CODE='W2', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00',
                           REPORT_NO='A0000005', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'),
                           ACC_TIME='0800',
                           LOC_CODE='1446', RAMP_FLAG='N', SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='02', HARM_EVENT_CODE2='02',
                           LOC_CASE_NO='153J11337',
                           ACRS_REPORT_NO='A0000005', REPORT_TYPE_CODE='03', LANE_NUMBER=2,
                           LANE_DIRECTION_CODE='04',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='02', TRAFFIC_CONTROL_CODE='01',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=2, INTER_AREA_CODE='00',
                           SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='VEHICLE 2 WAS PARKED AND UNOCCUPIED IN THE 200 BLOCK OF E. LAFAYETTE AVE. ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='03', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='01',
                           COLLISION_TYPE_CODE='03', SURF_COND_CODE='02', LANE_CODE='S1', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00',
                           REPORT_NO='A0000006', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'),
                           ACC_TIME='1920',
                           LOC_CODE='CAD#2388', RAMP_FLAG='N', SIGNAL_FLAG='Y', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='01', HARM_EVENT_CODE2='00',
                           LOC_CASE_NO='155J11449',
                           ACRS_REPORT_NO='A0000006', REPORT_TYPE_CODE='02', LANE_NUMBER=1,
                           LANE_DIRECTION_CODE='02',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00', TRAFFIC_CONTROL_CODE='03',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='Y', NUM_LANES=2, INTER_AREA_CODE='00',
                           SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='CC# 151011449 ON 10/26/15 AT APPROX. 1920 HOURS, V-2 WAS COMING TO A STOP ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='00',
                           COLLISION_TYPE_CODE='88', SURF_COND_CODE='A9.99', LANE_CODE='PP', RD_COND_CODE='A9.99',
                           FIX_OBJ_CODE='00',
                           REPORT_NO='A0000007', WEATHER_CODE='00', ACC_DATE=to_datetime('2015-10-26 00:00:00.000'),
                           ACC_TIME='1640',
                           LOC_CODE='CAD#1933', RAMP_FLAG='N', SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='02', HARM_EVENT_CODE2='00',
                           LOC_CASE_NO='155J11398',
                           ACRS_REPORT_NO='A0000007', REPORT_TYPE_CODE='03', LANE_NUMBER=0,
                           LANE_DIRECTION_CODE='00',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00', TRAFFIC_CONTROL_CODE='01',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=0, INTER_AREA_CODE='00',
                           SCHOOL_BUS_INVOLVED_CODE='01',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='THE CITY COMPLAINT NUMBER IS 5151011398. ON 10-26-2015 AT 1640HRS MS. W',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='00',
                           COLLISION_TYPE_CODE='03', SURF_COND_CODE='02', LANE_CODE='N3', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00',
                           REPORT_NO='A0000008', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'),
                           ACC_TIME='1704',
                           LOC_CODE='CAD#1959', RAMP_FLAG='N', SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='01', HARM_EVENT_CODE2='01',
                           LOC_CASE_NO='155J11389',
                           ACRS_REPORT_NO='A0000008', REPORT_TYPE_CODE='02', LANE_NUMBER=3,
                           LANE_DIRECTION_CODE='01',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00', TRAFFIC_CONTROL_CODE='01',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=3, INTER_AREA_CODE='00',
                           SCHOOL_BUS_INVOLVED_CODE='00',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='CC#5151011389 ON 10-26-15 AT 1704HRS V1, V2 AND V3 WERE TRAVELING NB ON  N ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='01', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='02',
                           COLLISION_TYPE_CODE='02', SURF_COND_CODE='02', LANE_CODE='N2', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00', REPORT_NO='A0000009', WEATHER_CODE='07.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'), ACC_TIME='1435',
                           LOC_CODE='CAD#1475', RAMP_FLAG='N', SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None,
                           AGENCY_CODE='AD', AREA_CODE='UNK', HARM_EVENT_CODE1='01', HARM_EVENT_CODE2='01',
                           LOC_CASE_NO='159J11324', ACRS_REPORT_NO='A0000009', REPORT_TYPE_CODE='02',
                           LANE_NUMBER=2, LANE_DIRECTION_CODE='01',
                           LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='01', TRAFFIC_CONTROL_CODE='00',
                           TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=4, INTER_AREA_CODE='02',
                           SCHOOL_BUS_INVOLVED_CODE='00',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='CC # 9-151091135 IS ASSIGNED TO SD PATROL. ON 10/26/15 @ 1535 HRS VH 1 WAS ',
                           GOV_PROPERTY_TXT=None),
            CrashSanitized(RAMP_MOVEMENT_CODE='A9.99', LIGHT_CODE='03', COUNTY_NO=24, MUNI_CODE=000,
                           JUNCTION_CODE='01',
                           COLLISION_TYPE_CODE='03', SURF_COND_CODE='02', LANE_CODE='N3', RD_COND_CODE='01',
                           FIX_OBJ_CODE='00', REPORT_NO='A0000010', WEATHER_CODE='06.01',
                           ACC_DATE=to_datetime('2015-10-26 00:00:00.000'), ACC_TIME='0212', LOC_CODE='0341',
                           RAMP_FLAG='N',
                           SIGNAL_FLAG='N', C_M_ZONE_FLAG='N', INTER_NUM=None, AGENCY_CODE='AD', AREA_CODE='UNK',
                           HARM_EVENT_CODE1='01', HARM_EVENT_CODE2='02', LOC_CASE_NO='151J10727',
                           ACRS_REPORT_NO='A0000010', REPORT_TYPE_CODE='03', LANE_NUMBER=3,
                           LANE_DIRECTION_CODE='01', LANE_TYPE_CODE='00', INTERSECTION_TYPE_CODE='00',
                           TRAFFIC_CONTROL_CODE='01', TRAFFIC_CONTROL_FUNCTION_FLAG='X', NUM_LANES=4,
                           INTER_AREA_CODE='00', SCHOOL_BUS_INVOLVED_CODE='00',
                           C_M_LOCATION_CODE='A9.99', C_M_CLOSURE_CODE='A9.99', C_M_WORKERS_PRESENT_FLAG='X',
                           NARRATIVE='UNIT 1 N/B IN LANE 3 OF 600-BLK N. PACA STREET AND STRIKES UNIT 2 FROM REAR.',
                           GOV_PROPERTY_TXT=None),

            # roadway sanitized (requires crash)
            RoadwaySanitized(REPORT_NO='A0000001', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='02', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME='3000 Tivoly Ave', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='N', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='1700 E 30th St',
                             ACC_DATE=to_datetime('2015-03-09 00:00:00.000'), X_COORDINATES=39.3254093476362,
                             Y_COORDINATES=-76.5919697284698, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='03',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=90600,
                             ROAD_NAME_CLEAN='TIVOLY AVE', REFERENCE_ROAD_NAME_CLEAN='30TH ST'),
            RoadwaySanitized(REPORT_NO='A0000002', ROUTE_NUMBER=1358, ROUTE_TYPE_CODE='MU', ROUTE_SUFFIX=None,
                             LOG_MILE=0.000, RD_CHAR_CODE='A8.98', RD_DIV_CODE='00', LOGMILE_DIR_FLAG='S',
                             ROAD_NAME='HARFORD AVE', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=0.000,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='S', FINAL_LOG_MILE=0.000,
                             REFERENCE_NUMBER=1359,
                             REFERENCE_TYPE_CODE='MU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='HARFORD AVE',
                             ACC_DATE=to_datetime('2015-03-22 00:00:00.000'), X_COORDINATES=39.350734499734,
                             Y_COORDINATES=-76.5519082546234, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='01',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=270402,
                             ROAD_NAME_CLEAN='HARFORD AVE', REFERENCE_ROAD_NAME_CLEAN='HARFORD AVE'),
            RoadwaySanitized(REPORT_NO='A0000003', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='A9.99', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME=None, FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='X', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME=None,
                             ACC_DATE=to_datetime('2015-05-30 00:00:00.000'), X_COORDINATES=39.3127775725174,
                             Y_COORDINATES=-76.6199800372124, RD_ALIGNMENT_CODE='A9.99', RD_GRADE_CODE='A9.99',
                             OFF_ROAD_TXT='Parking Lot', CENSUS_TRACT=120700,
                             ROAD_NAME_CLEAN='HARFORD AVE', REFERENCE_ROAD_NAME_CLEAN='HARFORD AVE'),
            RoadwaySanitized(REPORT_NO='A0000004', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='02', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME='Elm Ave', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='S', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='Mill Rd',
                             ACC_DATE=to_datetime('2015-02-23 00:00:00.000'), X_COORDINATES=39.3246945589931,
                             Y_COORDINATES=-76.6310857236385, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='01',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=130600,
                             ROAD_NAME_CLEAN='ELM AVE', REFERENCE_ROAD_NAME_CLEAN='MILL RD'),
            RoadwaySanitized(REPORT_NO='A0000005', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='88', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME='Narcissus Ave', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='S', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='Manhattan Ave',
                             ACC_DATE=to_datetime('2015-04-01 00:00:00.000'), X_COORDINATES=39.3520313162612,
                             Y_COORDINATES=-76.6871076822281, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='01',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=271900,
                             ROAD_NAME_CLEAN='NARCISSUS AVE', REFERENCE_ROAD_NAME_CLEAN='MANHATTAN AVE'),
            RoadwaySanitized(REPORT_NO='A0000006', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='A9.99', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME=None, FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='X', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME=None,
                             ACC_DATE=to_datetime('2015-03-31 00:00:00.000'), X_COORDINATES=39.3571390148285,
                             Y_COORDINATES=-76.5807902812958, RD_ALIGNMENT_CODE='A9.99', RD_GRADE_CODE='A9.99',
                             OFF_ROAD_TXT='East Beleveder Ave Beechdale Ave', CENSUS_TRACT=270803,
                             ROAD_NAME_CLEAN='NARCISSUS AVE', REFERENCE_ROAD_NAME_CLEAN='MANHATTAN AVE'),
            RoadwaySanitized(REPORT_NO='A0000007', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='03', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME='gwynn falls parkway', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='W', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='roslyn ave',
                             ACC_DATE=to_datetime('2015-05-29 00:00:00.000'), X_COORDINATES=39.3139303489926,
                             Y_COORDINATES=-76.6781437397003, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='01',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=150800,
                             ROAD_NAME_CLEAN='GWYNN FALLS PKWY', REFERENCE_ROAD_NAME_CLEAN='ROSLYN AVE'),
            RoadwaySanitized(REPORT_NO='A0000008', ROUTE_NUMBER=140, ROUTE_TYPE_CODE='MD', ROUTE_SUFFIX=None,
                             LOG_MILE=5.143, RD_CHAR_CODE='A8.98', RD_DIV_CODE='01', LOGMILE_DIR_FLAG='S',
                             ROAD_NAME='MONROE ST (SB COUPLET)', FUNCTIONAL_CLASS_NO=None, TC_CODE=None,
                             DISTANCE=0.000,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='S', FINAL_LOG_MILE=5.143, REFERENCE_NUMBER=0,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='WALBROOK AVE',
                             ACC_DATE=to_datetime('2015-05-26 00:00:00.000'), X_COORDINATES=39.31088494421,
                             Y_COORDINATES=-76.6484329104424, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='01',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=150400,
                             ROAD_NAME_CLEAN='MONROE ST', REFERENCE_ROAD_NAME_CLEAN='WALBROOK AVE'),
            RoadwaySanitized(REPORT_NO='A0000009', ROUTE_NUMBER=None, ROUTE_TYPE_CODE='UU', ROUTE_SUFFIX=None,
                             LOG_MILE=None, RD_CHAR_CODE='A8.98', RD_DIV_CODE='01', LOGMILE_DIR_FLAG='X',
                             ROAD_NAME='EXETER HALL AVE', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=None,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='W', FINAL_LOG_MILE=999.003,
                             REFERENCE_NUMBER=None,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='LOCH RAVEN RD',
                             ACC_DATE=to_datetime('2015-04-17 00:00:00.000'), X_COORDINATES=39.3220251893659,
                             Y_COORDINATES=-76.6041710972786, RD_ALIGNMENT_CODE=88, RD_GRADE_CODE='04',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=90400,
                             ROAD_NAME_CLEAN='EXETER HALL AVE', REFERENCE_ROAD_NAME_CLEAN='LOCH RAVEN RD'),
            RoadwaySanitized(REPORT_NO='A0000010', ROUTE_NUMBER=43, ROUTE_TYPE_CODE='MU', ROUTE_SUFFIX=None,
                             LOG_MILE=0.900, RD_CHAR_CODE='A8.98', RD_DIV_CODE='01', LOGMILE_DIR_FLAG='N',
                             ROAD_NAME='S MONROE ST', FUNCTIONAL_CLASS_NO=None, TC_CODE=None, DISTANCE=0.000,
                             FEET_MILES_FLAG='M', DISTANCE_DIR_FLAG='S', FINAL_LOG_MILE=0.900, REFERENCE_NUMBER=0,
                             REFERENCE_TYPE_CODE='UU', REFERENCE_SUFFIX=None, REFERENCE_ROAD_NAME='MT. CLARE PARK',
                             ACC_DATE=to_datetime('2015-05-12 00:00:00.000'), X_COORDINATES=39.2776807823985,
                             Y_COORDINATES=-76.6451820731163, RD_ALIGNMENT_CODE='01', RD_GRADE_CODE='04',
                             OFF_ROAD_TXT=None, CENSUS_TRACT=210200,
                             ROAD_NAME_CLEAN='MONROE ST', REFERENCE_ROAD_NAME_CLEAN='MT CLARE PARK'),

            # vehicles sanitized (requires crash)
            VehicleSanitized(HARM_EVENT_CODE='09', PERSON_ID=None, CONTI_DIRECTION_CODE='03', DAMAGE_CODE='04',
                             MOVEMENT_CODE='01', REPORT_NO='A0000001', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2011',
                             VEH_MAKE='HONDA', COMMERCIAL_FLAG=None, VEH_MODEL='ACCORD', TOWED_AWAY_FLAG='Y',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='02', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=50,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849671,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=2015, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='08', AREA_DAMAGED_CODE_MAIN='08',
                             ACC_DATE=to_datetime('2015-05-18 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY='McDells # 14',
                             REMOVED_TO='City Yard', VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='03', DAMAGE_CODE='02',
                             MOVEMENT_CODE='01', REPORT_NO='A0000002', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='0',
                             VEH_MAKE='UNKNOWN', COMMERCIAL_FLAG=None, VEH_MODEL='UNKNOWN', TOWED_AWAY_FLAG='X',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='03', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='Y', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=30,
                             HIT_AND_RUN_FLAG='Y', HAZMAT_SPILL_FLAG='X', VIN_NO=8849672,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=None, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='02', AREA_DAMAGED_CODE_MAIN='02',
                             ACC_DATE=to_datetime('2015-05-18 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='03', DAMAGE_CODE='02',
                             MOVEMENT_CODE='01', REPORT_NO='A0000003', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2011',
                             VEH_MAKE='SUBARU', COMMERCIAL_FLAG=None, VEH_MODEL='OUTBACK', TOWED_AWAY_FLAG='N',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='03', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='Y', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=30,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849673,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=2016, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='10', AREA_DAMAGED_CODE_MAIN='09',
                             ACC_DATE=to_datetime('2015-05-18 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='01', DAMAGE_CODE='99',
                             MOVEMENT_CODE='01', REPORT_NO='A0000004', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='0',
                             VEH_MAKE='BUICK', COMMERCIAL_FLAG=None, VEH_MODEL='UNK', TOWED_AWAY_FLAG='X',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='03', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='X', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=25,
                             HIT_AND_RUN_FLAG='Y', HAZMAT_SPILL_FLAG='X', VIN_NO=8849674,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE=None,
                             PLATE_YEAR=2015, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='99', AREA_DAMAGED_CODE_MAIN='99',
                             ACC_DATE=to_datetime('2015-05-02 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE=None),
            VehicleSanitized(HARM_EVENT_CODE='00', PERSON_ID=None, CONTI_DIRECTION_CODE='04', DAMAGE_CODE='02',
                             MOVEMENT_CODE='01', REPORT_NO='A0000005', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='1996',
                             VEH_MAKE='HONDA', COMMERCIAL_FLAG=None, VEH_MODEL='CIVIC LX', TOWED_AWAY_FLAG='X',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='04', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='X', NUM_OCC=2, PARKED_FLAG='N', SPEED_LIMIT=25,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849675,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=2015, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='11', AREA_DAMAGED_CODE_MAIN='11',
                             ACC_DATE=to_datetime('2015-05-02 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='01', DAMAGE_CODE='99',
                             MOVEMENT_CODE='11', REPORT_NO='A0000006', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2013',
                             VEH_MAKE='CHEVY', COMMERCIAL_FLAG=None, VEH_MODEL='UNK', TOWED_AWAY_FLAG='X',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='02', BODY_TYPE_CODE='26.88',
                             DRIVERLESS_FLAG='U', FIRE_FLAG='X', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=0,
                             HIT_AND_RUN_FLAG='Y', HAZMAT_SPILL_FLAG='X', VIN_NO=8849676,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=None, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='A9.99',
                             AREA_DAMAGED_CODE_MAIN='A9.99',
                             ACC_DATE=to_datetime('2015-05-18 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MA'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='01', DAMAGE_CODE='03',
                             MOVEMENT_CODE='03', REPORT_NO='A0000007', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2011',
                             VEH_MAKE='HONDA', COMMERCIAL_FLAG=None, VEH_MODEL='ACCORD', TOWED_AWAY_FLAG='X',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='01', BODY_TYPE_CODE='23',
                             DRIVERLESS_FLAG='U', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=0,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849677,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=None, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='12', AREA_DAMAGED_CODE_MAIN='A9.99',
                             ACC_DATE=to_datetime('2015-05-18 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY=None,
                             REMOVED_TO=None, VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='04', DAMAGE_CODE='04',
                             MOVEMENT_CODE='01', REPORT_NO='A0000008', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2007',
                             VEH_MAKE='ACURA', COMMERCIAL_FLAG=None, VEH_MODEL='TL', TOWED_AWAY_FLAG='Y',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='04', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='N', NUM_OCC=2, PARKED_FLAG='N', SPEED_LIMIT=25,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849678,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=2016, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='11', AREA_DAMAGED_CODE_MAIN='11',
                             ACC_DATE=to_datetime('2015-05-08 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY='owners',
                             REMOVED_TO='arrangements', VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='Y',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='01', DAMAGE_CODE='04',
                             MOVEMENT_CODE='01', REPORT_NO='A0000009', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2012',
                             VEH_MAKE='HYUN', COMMERCIAL_FLAG=None, VEH_MODEL='4D', TOWED_AWAY_FLAG='Y',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='01', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=25,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849679,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=2016, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='12', AREA_DAMAGED_CODE_MAIN='12',
                             ACC_DATE=to_datetime('2015-05-08 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY='owners',
                             REMOVED_TO='arrangements', VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='Y',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),
            VehicleSanitized(HARM_EVENT_CODE='01', PERSON_ID=None, CONTI_DIRECTION_CODE='01', DAMAGE_CODE='04',
                             MOVEMENT_CODE='12', REPORT_NO='A0000010', CV_BODY_TYPE_CODE='A9.99', VEH_YEAR='2014',
                             VEH_MAKE='MAZDA', COMMERCIAL_FLAG=None, VEH_MODEL='3', TOWED_AWAY_FLAG='Y',
                             NUM_AXLES=None, GVW_CODE=None, GOING_DIRECTION_CODE='03', BODY_TYPE_CODE='02',
                             DRIVERLESS_FLAG='N', FIRE_FLAG='N', NUM_OCC=1, PARKED_FLAG='N', SPEED_LIMIT=35,
                             HIT_AND_RUN_FLAG='N', HAZMAT_SPILL_FLAG='X', VIN_NO=8849680,
                             TOWED_VEHICLE_CONFIG_CODE='00',
                             TOWED_VEHICLE_CODE2='A8.98', TOWED_VEHICLE_CODE3='A8.98', PLATE_STATE='MD',
                             PLATE_YEAR=None, AREA_DAMAGED_CODE1='00', AREA_DAMAGED_CODE2='00',
                             AREA_DAMAGED_CODE3='00', AREA_DAMAGED_CODE_IMP1='11', AREA_DAMAGED_CODE_MAIN='11',
                             ACC_DATE=to_datetime('2015-05-12 00:00:00.000'), SEQ_EVENT_CODE1='00',
                             SEQ_EVENT_CODE2='00',
                             SEQ_EVENT_CODE3='00', SEQ_EVENT_CODE4='00', REMOVED_BY='greenwood 124',
                             REMOVED_TO='cityyard', VEH_SPECIAL_FUNCTION_CODE=None, EMERGENCY_USE_FLAG='N',
                             CV_CONFIG_CODE='A9.99', BUS_USE_CODE='A9.99', HZM_NUM=None, PLACARD_VISIBLE_FLAG='X',
                             VEHICLE_WEIGHT_CODE='A9.99', OWNER_STATE_CODE='MD'),

            # ems sanitized ( requires crash)
            EmsSanitized(EMS_ID=748307, REPORT_NO='A0000001', RUN_REP_NO='A0000001', EMS_UNIT_TAKEN_BY='MEDIC 22',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='HARBOR HOSPITAL', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-01 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748364, REPORT_NO='A0000002', RUN_REP_NO='A0000002', EMS_UNIT_TAKEN_BY='MEDIC 1',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='UNIVERSITY', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-03 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748365, REPORT_NO='A0000003', RUN_REP_NO='A0000003', EMS_UNIT_TAKEN_BY='MEDIC 23',
                         EMS_UNIT_LABEL='B', EMS_UNIT_TAKEN_TO='UNIVERSITY', EMS_SNO=2,
                         ACC_DATE=to_datetime('2015-01-03 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748369, REPORT_NO='A0000004', RUN_REP_NO='A0000004', EMS_UNIT_TAKEN_BY='MEDIC 3',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='SINAI', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-04 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748375, REPORT_NO='A0000005', RUN_REP_NO='UNKNOWN', EMS_UNIT_TAKEN_BY='MEDIC 18',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='SINAI HOSPITAL', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-04 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748464, REPORT_NO='A0000006', RUN_REP_NO='A0000005', EMS_UNIT_TAKEN_BY='MEDIC 1',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='MERCY', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-03 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748113, REPORT_NO='A0000007', RUN_REP_NO='A0000006', EMS_UNIT_TAKEN_BY='MEDIC 4',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='SINAI', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-01 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748376, REPORT_NO='A0000008', RUN_REP_NO='UNKNOWN',
                         EMS_UNIT_TAKEN_BY='SINAI HOSPITAL',
                         EMS_UNIT_LABEL='B', EMS_UNIT_TAKEN_TO='MEDIC 18', EMS_SNO=2,
                         ACC_DATE=to_datetime('2015-01-04 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748377, REPORT_NO='A0000009', RUN_REP_NO='UNKNOWN',
                         EMS_UNIT_TAKEN_BY='BALTIMORE CO. MEDIC 2',
                         EMS_UNIT_LABEL='C', EMS_UNIT_TAKEN_TO='SINAI HOSPITAL', EMS_SNO=3,
                         ACC_DATE=to_datetime('2015-01-04 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
            EmsSanitized(EMS_ID=748388, REPORT_NO='A0000010', RUN_REP_NO='A0000010',
                         EMS_UNIT_TAKEN_BY='BALTIMORE CITY MEDIC 5',
                         EMS_UNIT_LABEL='A', EMS_UNIT_TAKEN_TO='UNIVERSITY OF MARYLAND HOSPITAL', EMS_SNO=1,
                         ACC_DATE=to_datetime('2015-01-04 00:00:00.000'), EMS_TRANSPORT_TYPE_FLAG=None),
        ])
        session.commit()

        session.add_all([
            # person sanitized (requires VEHICLE_ID and crash)
            PersonSanitized(SEX='02', CONDITION_CODE='01', DR_UNIT='01', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000001', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=58, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='01', BAC=None, FAULT_FLAG='Y', EQUIP_PROB_CODE='01',
                            SAF_EQUIP_CODE='99', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='01',
                            DRIVER_DOB=to_datetime('1956-10-05 00:00:00.000'), PERSON_ID=13373371, STATE_CODE='MD',
                            CLASS=None,
                            CDL_FLAG='N', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-05-13 00:00:00.000'),
                            VEHICLE_ID=8849671, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='99', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='01', CONDITION_CODE='01', DR_UNIT='02', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000002', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=54, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='01', BAC=None, FAULT_FLAG='N', EQUIP_PROB_CODE='01',
                            SAF_EQUIP_CODE='13', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='01',
                            DRIVER_DOB=to_datetime('1961-04-05 00:00:00.000'), PERSON_ID=13373372, STATE_CODE='MD',
                            CLASS=None,
                            CDL_FLAG='N', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-05-13 00:00:00.000'),
                            VEHICLE_ID=8849672, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='00', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='99', CONDITION_CODE='A9.99', DR_UNIT='03', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000003', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=999, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='A9.99', BAC=None, FAULT_FLAG='X', EQUIP_PROB_CODE='A9.99',
                            SAF_EQUIP_CODE='A9.99', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='A9.99',
                            DRIVER_DOB=None, PERSON_ID=13373373, STATE_CODE=None, CLASS=None,
                            CDL_FLAG='X', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-05-13 00:00:00.000'),
                            VEHICLE_ID=8849673, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='A9.99', DISTRACTED_BY_CODE='A9.99', ALCO_TEST_CODE='A9.99',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='A9.99', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='99', CONDITION_CODE='99', DR_UNIT='01', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000004', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=999, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='99', BAC=None, FAULT_FLAG='Y', EQUIP_PROB_CODE='99',
                            SAF_EQUIP_CODE='99', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='01',
                            DRIVER_DOB=to_datetime('2015-04-10 00:00:00.000'), PERSON_ID=13373374, STATE_CODE='MD',
                            CLASS=None,
                            CDL_FLAG='N', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-04-10 00:00:00.000'),
                            VEHICLE_ID=8849674, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='00', ALCO_TEST_CODE='99',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='99', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='01', CONDITION_CODE='02', DR_UNIT='00', INJ_SEVER_CODE='03', PED_UNIT='01',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000005', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE='03', PED_LOCATION_CODE='88', PED_OBEY_CODE='01', PED_TYPE_CODE='01',
                            MOVEMENT_CODE='88', PERSON_TYPE='P', AGE=25, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='21', BAC=None, FAULT_FLAG='U', EQUIP_PROB_CODE=None,
                            SAF_EQUIP_CODE='01', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE=None,
                            DRIVER_DOB=to_datetime('1989-05-11 00:00:00.000'), PERSON_ID=13373375, STATE_CODE='DE',
                            CLASS=None,
                            CDL_FLAG=None, ALCO_DRUG_IMPAIRED_FLAG='A',
                            ACC_DATE=to_datetime('2015-04-10 00:00:00.000'),
                            VEHICLE_ID=None, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1='08',
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE=None, DISTRACTED_BY_CODE=None, ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='02', CONDITION_CODE='01', DR_UNIT='02', INJ_SEVER_CODE='03', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000006', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=29, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='00', BAC=None, FAULT_FLAG='Y', EQUIP_PROB_CODE='01',
                            SAF_EQUIP_CODE='13', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='01',
                            DRIVER_DOB=to_datetime('1985-08-14 00:00:00.000'), PERSON_ID=13373376, STATE_CODE='MD',
                            CLASS=None,
                            CDL_FLAG='N', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-03-06 00:00:00.000'),
                            VEHICLE_ID=8849676, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='00', DISTRACTED_BY_CODE='00', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='01', CONDITION_CODE='01', DR_UNIT='01', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000007', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=54, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='01', BAC=None, FAULT_FLAG='Y', EQUIP_PROB_CODE='01',
                            SAF_EQUIP_CODE='13', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='01',
                            DRIVER_DOB=to_datetime('1961-02-25 00:00:00.000'), PERSON_ID=13373377, STATE_CODE='MD',
                            CLASS=None,
                            CDL_FLAG='Y', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-02-27 00:00:00.000'),
                            VEHICLE_ID=8849677, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='00', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='99', CONDITION_CODE='00', DR_UNIT='01', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000008', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=999, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='00', BAC=None, FAULT_FLAG='Y', EQUIP_PROB_CODE='00',
                            SAF_EQUIP_CODE='01', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='00',
                            DRIVER_DOB=None, PERSON_ID=13373378, STATE_CODE=None, CLASS=None,
                            CDL_FLAG='N', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-02-24 00:00:00.000'),
                            VEHICLE_ID=8849678, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='01', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='99', CONDITION_CODE='A9.99', DR_UNIT='02', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000009', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=999, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='A9.99', BAC=None, FAULT_FLAG='X', EQUIP_PROB_CODE='A9.99',
                            SAF_EQUIP_CODE='A9.99', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='A9.99',
                            DRIVER_DOB=None, PERSON_ID=13373379, STATE_CODE=None, CLASS=None,
                            CDL_FLAG='X', ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-02-24 00:00:00.000'),
                            VEHICLE_ID=8849679, EMS_UNIT_LABEL=None, EMS_ID=None, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='A9.99', DISTRACTED_BY_CODE='A9.99', ALCO_TEST_CODE='A9.99',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='A9.99', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),
            PersonSanitized(SEX='02', CONDITION_CODE='01', DR_UNIT='01', INJ_SEVER_CODE='01', PED_UNIT='00',
                            OCC_UNIT='00', OCC_NUM=None, REPORT_NO='A0000010', OCC_SEAT_POS_CODE=None,
                            PED_VISIBLE_CODE=None, PED_LOCATION_CODE=None, PED_OBEY_CODE=None, PED_TYPE_CODE=None,
                            MOVEMENT_CODE=None, PERSON_TYPE='D', AGE=39, SUBST_TEST_CODE='A8.98',
                            SUBST_USE_CODE='01', BAC=None, FAULT_FLAG='N', EQUIP_PROB_CODE='00',
                            SAF_EQUIP_CODE='13', WOULD_HAVE_LIVED_FLAG=None, EJECT_CODE='00',
                            DRIVER_DOB=to_datetime('1976-05-05 00:00:00.000'), PERSON_ID=13373380, STATE_CODE='MD',
                            CLASS='c',
                            CDL_FLAG=None, ALCO_DRUG_IMPAIRED_FLAG='N',
                            ACC_DATE=to_datetime('2015-05-23 00:00:00.000'),
                            VEHICLE_ID=8849680, EMS_UNIT_LABEL='A', EMS_ID=759628, NONMOTOR_ACTION_TIME_CODE1=None,
                            NONMOTOR_ACTION_TIME_CODE2='A7.97', NONMOTOR_PRIOR_CODE='A7.97', UNIT_FIRST_STRIKE=None,
                            AIR_BAG_CODE='01', DISTRACTED_BY_CODE='00', ALCO_TEST_CODE='00',
                            ALCO_TEST_TYPE_CODE='A9.99', DRUG_TEST_CODE='00', DRUG_TEST_RESULT_FLAG='X',
                            OCC_SEAT_LOCATION=None, OCC_SEAT_ROW=None, OCC_POS_INROW_CODE=None),

            # circumstance_sanitized (requires crash, person, vehicle)
            CircumstanceSanitized(REPORT_NO='A0000001', CONTRIB_CODE1='99', CONTRIB_CODE2='53', CONTRIB_CODE3=None,
                                  CONTRIB_CODE4='76.88', PERSON_ID=None, VEHICLE_ID=8849671, CIRCUMSTANCE_ID=11458081,
                                  ACC_DATE=to_datetime('2015-03-21 00:00:00.000'), CONTRIB_FLAG='V'),
            # The following has invalid contrib codes
            CircumstanceSanitized(REPORT_NO='A0000002', CONTRIB_CODE1='88', CONTRIB_CODE2='78', CONTRIB_CODE3='69.88',
                                  CONTRIB_CODE4=None, PERSON_ID=None, VEHICLE_ID=8849672, CIRCUMSTANCE_ID=11458083,
                                  ACC_DATE=to_datetime('2015-03-21 00:00:00.000'), CONTRIB_FLAG='V'),
            CircumstanceSanitized(REPORT_NO='A0000003', CONTRIB_CODE1=00, CONTRIB_CODE2=00, CONTRIB_CODE3=00,
                                  CONTRIB_CODE4=00, PERSON_ID=None, VEHICLE_ID=None, CIRCUMSTANCE_ID=11458079,
                                  ACC_DATE=to_datetime('2015-03-21 00:00:00.000'), CONTRIB_FLAG='E'),
            CircumstanceSanitized(REPORT_NO='A0000004', CONTRIB_CODE1='88', CONTRIB_CODE2='78', CONTRIB_CODE3='69.88',
                                  CONTRIB_CODE4=None, PERSON_ID=None, VEHICLE_ID=None, CIRCUMSTANCE_ID=11458080,
                                  ACC_DATE=to_datetime('2015-03-21 00:00:00.000'), CONTRIB_FLAG='R'),
            CircumstanceSanitized(REPORT_NO='A0000005', CONTRIB_CODE1=00, CONTRIB_CODE2='A9.99',
                                  CONTRIB_CODE3='A9.99',
                                  CONTRIB_CODE4='A9.99', PERSON_ID=13373371, VEHICLE_ID=8849672,
                                  CIRCUMSTANCE_ID=11458084,
                                  ACC_DATE=to_datetime('2015-03-21 00:00:00.000'), CONTRIB_FLAG='D'),
            CircumstanceSanitized(REPORT_NO='A0000006', CONTRIB_CODE1=00, CONTRIB_CODE2='A9.99',
                                  CONTRIB_CODE3='A9.99',
                                  CONTRIB_CODE4='A9.99', PERSON_ID=13373373, VEHICLE_ID=8849676,
                                  CIRCUMSTANCE_ID=11458098,
                                  ACC_DATE=to_datetime('2015-03-10 00:00:00.000'), CONTRIB_FLAG='D'),
            CircumstanceSanitized(REPORT_NO='A0000007', CONTRIB_CODE1=00, CONTRIB_CODE2='A9.99',
                                  CONTRIB_CODE3='A9.99',
                                  CONTRIB_CODE4='A9.99', PERSON_ID=13373375, VEHICLE_ID=8849677,
                                  CIRCUMSTANCE_ID=11458100,
                                  ACC_DATE=to_datetime('2015-03-10 00:00:00.000'), CONTRIB_FLAG='D'),
            CircumstanceSanitized(REPORT_NO='A0000008', CONTRIB_CODE1=41, CONTRIB_CODE2=00, CONTRIB_CODE3=00,
                                  CONTRIB_CODE4=00, PERSON_ID=None, VEHICLE_ID=None, CIRCUMSTANCE_ID=11458095,
                                  ACC_DATE=to_datetime('2015-03-10 00:00:00.000'), CONTRIB_FLAG='E'),
            # The following has invalid contrib codes
            CircumstanceSanitized(REPORT_NO='A0000009', CONTRIB_CODE1='99', CONTRIB_CODE2='53', CONTRIB_CODE3='83.88',
                                  CONTRIB_CODE4='76.88', PERSON_ID=None, VEHICLE_ID=None, CIRCUMSTANCE_ID=11458096,
                                  ACC_DATE=to_datetime('2015-03-10 00:00:00.000'), CONTRIB_FLAG='R'),

            # citation codes (requires person and crash)
            CitationCodeSanitized(CITATION='JE48479', PERSON_ID='13373371', REPORT_NO='A0000001',
                                  ACC_DATE=to_datetime('2015-03-08 00:00:00.000'), CITATION_ID='1758204'),
            CitationCodeSanitized(CITATION='JJ98369', PERSON_ID='13373372', REPORT_NO='A0000002',
                                  ACC_DATE=to_datetime('2015-03-08 00:00:00.000'), CITATION_ID='1758529'),
            CitationCodeSanitized(CITATION='GN73617', PERSON_ID='13373373', REPORT_NO='A0000003',
                                  ACC_DATE=to_datetime('2015-03-14 00:00:00.000'), CITATION_ID='1758541'),
            CitationCodeSanitized(CITATION='GN73616', PERSON_ID='13373374', REPORT_NO='A0000004',
                                  ACC_DATE=to_datetime('2015-03-14 00:00:00.000'), CITATION_ID='1758542'),
            CitationCodeSanitized(CITATION='JE52651-JE52661', PERSON_ID='13373375', REPORT_NO='A0000005',
                                  ACC_DATE=to_datetime('2015-03-10 00:00:00.000'), CITATION_ID='1758295'),
            CitationCodeSanitized(CITATION='JK42951,52,53', PERSON_ID='13373376', REPORT_NO='A0000006',
                                  ACC_DATE=to_datetime('2015-03-05 00:00:00.000'), CITATION_ID='1758471'),
            CitationCodeSanitized(CITATION='JC95178', PERSON_ID='13373377', REPORT_NO='A0000007',
                                  ACC_DATE=to_datetime('2015-02-23 00:00:00.000'), CITATION_ID='1758304'),
            CitationCodeSanitized(CITATION='JC95179', PERSON_ID='13373378', REPORT_NO='A0000008',
                                  ACC_DATE=to_datetime('2015-02-23 00:00:00.000'), CITATION_ID='1758305'),
            CitationCodeSanitized(CITATION='JC95180', PERSON_ID='13373379', REPORT_NO='A0000009',
                                  ACC_DATE=to_datetime('2015-02-23 00:00:00.000'), CITATION_ID='1758306'),
            CitationCodeSanitized(CITATION='21-309(b)', PERSON_ID='13373380', REPORT_NO='A0000010',
                                  ACC_DATE=to_datetime('2015-03-11 00:00:00.000'), CITATION_ID='1758326'),

            # trailer sanitized (requires crash)
            TrailerSanitized(TRAILER_RECORD_ID=8859, REPORT_NO='A0000001',
                             ACC_DATE=to_datetime('2015-11-30 00:00:00.000'),
                             VEHICLE_ID=9001795, REFERENCE_UNIT_NO='02', TOWED_VEHICLE_UNIT_NO='01',
                             VEH_YEAR='2015',
                             VEH_MAKE='UNKNOWN', VEH_MODEL='UNKNOWN', BODY_TYPE_CODE='07', PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=8557, REPORT_NO='A0000002',
                             ACC_DATE=to_datetime('2015-11-01 00:00:00.000'),
                             VEHICLE_ID=8989956, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO='01',
                             VEH_YEAR='2015',
                             VEH_MAKE='NISSAN', VEH_MODEL='ALTI', BODY_TYPE_CODE='06', PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=4363, REPORT_NO='A0000003',
                             ACC_DATE=to_datetime('2015-01-15 00:00:00.000'),
                             VEHICLE_ID=8817597, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO=None, VEH_YEAR='8',
                             VEH_MAKE='NISSAN', VEH_MODEL='ALTIMA', BODY_TYPE_CODE=None, PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=4364, REPORT_NO='A0000004',
                             ACC_DATE=to_datetime('2015-01-15 00:00:00.000'),
                             VEHICLE_ID=8817598, REFERENCE_UNIT_NO='02', TOWED_VEHICLE_UNIT_NO=None, VEH_YEAR='97',
                             VEH_MAKE='NISSAN', VEH_MODEL='MAXIMA', BODY_TYPE_CODE=None, PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=4372, REPORT_NO='A0000005',
                             ACC_DATE=to_datetime('2015-01-26 00:00:00.000'),
                             VEHICLE_ID=8818251, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO=None,
                             VEH_YEAR='2012',
                             VEH_MAKE='NISSAN', VEH_MODEL='VERSA', BODY_TYPE_CODE=None, PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=8389, REPORT_NO='A0000006',
                             ACC_DATE=to_datetime('2015-10-05 00:00:00.000'),
                             VEHICLE_ID=8982530, REFERENCE_UNIT_NO='02', TOWED_VEHICLE_UNIT_NO='01',
                             VEH_YEAR='2013',
                             VEH_MAKE='TRAO', VEH_MODEL='FB', BODY_TYPE_CODE='03', PLATE_STATE='TX',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=9246, REPORT_NO='A0000007',
                             ACC_DATE=to_datetime('2015-12-08 00:00:00.000'),
                             VEHICLE_ID=9014777, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO='01', VEH_YEAR='0',
                             VEH_MAKE='UNKNOWN', VEH_MODEL='UNKNOWN', BODY_TYPE_CODE='01', PLATE_STATE='SC',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=9431, REPORT_NO='A0000008',
                             ACC_DATE=to_datetime('2015-12-21 00:00:00.000'),
                             VEHICLE_ID=9022050, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO='01',
                             VEH_YEAR='2012',
                             VEH_MAKE='NISSAN', VEH_MODEL='SENTRA', BODY_TYPE_CODE='88', PLATE_STATE='MD',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=6306, REPORT_NO='A0000009',
                             ACC_DATE=to_datetime('2015-03-31 00:00:00.000'),
                             VEHICLE_ID=8865947, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO=None,
                             VEH_YEAR='2007',
                             VEH_MAKE='WABA', VEH_MODEL='SE', BODY_TYPE_CODE=None, PLATE_STATE='ME',
                             PLATE_YEAR=None),
            TrailerSanitized(TRAILER_RECORD_ID=6611, REPORT_NO='A0000010',
                             ACC_DATE=to_datetime('2015-02-25 00:00:00.000'),
                             VEHICLE_ID=8878854, REFERENCE_UNIT_NO='01', TOWED_VEHICLE_UNIT_NO=None,
                             VEH_YEAR='2003',
                             VEH_MAKE='TOP', VEH_MODEL='TL', BODY_TYPE_CODE=None, PLATE_STATE='MD',
                             PLATE_YEAR=None),
        ])
        session.commit()

    return conn_str


@pytest.fixture(name='conn_str_unsanitized')
def sanitized_crash_database(tmpdir):
    """Fixture for the WorksheetMaker class"""
    conn_str = 'sqlite:///{}'.format(os.path.join(tmpdir, 'crashdatabase.db'))

    # Make the database
    engine = create_engine(conn_str, echo=True, future=True)

    with engine.begin() as connection:
        CDBase.metadata.create_all(connection)

    with Session(bind=engine) as session:
        session.add_all([
            Roadway(ROADID='R0000001'),
            Crash(REPORTNUMBER='A0000001',
                  ROADID='R0000001'),
            Crash(REPORTNUMBER='A0000002',
                  ROADID='R0000001'),
            CrashDiagram(REPORTNUMBER='A0000001',
                         CRASHDIAGRAM=('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQO'
                                       'bYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII=')),
            CrashDiagram(REPORTNUMBER='A0000002',
                         CRASHDIAGRAM='#$%$#^%$^$%FDGSFGSDGFDSG====================='),
            PdfReport(REPORTNUMBER='A0000001',
                      PDF_ID=123456,
                      PDFREPORT1=('JVBERi0xLjYNJeLjz9MNCjI0IDAgb2JqDTw8L0ZpbHRlci9GbGF0ZURlY29kZS9GaXJzdCA0L0xlbmd0aCA'
                                  'yMTYvTiAxL1R5cGUvT2JqU3RtPj5zdHJlYW0NCmjePI9RS8MwFIX/yn1bi9jepCQ6GYNpFBTEMsW97CVLbjW'
                                  'YNpImmz/fVsXXcw/f/c4SEFarepPTe4iFok8dU09DgtDBQx6TMwT74vaLTE7uSPDUdXM0Xe/73r1FnVwYYEt'
                                  'HR6d9WdY3kX4ipRMV6oojSmxQMoGyac5RLBAXf63p38aGA7XPorLewyvFcYaJile8rB+D/YcwiRdMMGScszO'
                                  '8/IW0MdhsaKKYGA46gXKTr/cUQVY4We/cYMNpnLVeXPJUXHs9fECr7kAFk+eZ5Xr9LcAAfKpQrA0KZW5kc3R'
                                  'yZWFtDWVuZG9iag0yNSAwIG9iag08PC9GaWx0ZXIvRmxhdGVEZWNvZGUvRmlyc3QgNC9MZW5ndGggNDkvTiA'
                                  'xL1R5cGUvT2JqU3RtPj5zdHJlYW0NCmjeslAwULCx0XfOL80rUTDU985MKY42NAIKBsXqh1QWpOoHJKanFtv'
                                  'ZAQQYAN/6C60NCmVuZHN0cmVhbQ1lbmRvYmoNMjYgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0ZpcnN'
                                  '0IDkvTGVuZ3RoIDQyL04gMi9UeXBlL09ialN0bT4+c3RyZWFtDQpo3jJTMFAwVzC0ULCx0fcrzS2OBnENFIJ'
                                  'i7eyAIsH6LnZ2AAEGAI2FCDcNCmVuZHN0cmVhbQ1lbmRvYmoNMjcgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGV'
                                  'jb2RlL0ZpcnN0IDUvTGVuZ3RoIDEyMC9OIDEvVHlwZS9PYmpTdG0+PnN0cmVhbQ0KaN4yNFIwULCx0XfOzyt'
                                  'JzSspVjAyBgoE6TsX5Rc45VdEGwB5ZoZGCuaWRrH6vqkpmYkYogGJRUCdChZgfUGpxfmlRcmpxUAzA4ryk4N'
                                  'TS6L1A1zc9ENSK0pi7ez0g/JLEktSFQz0QyoLUoF601Pt7AACDADYoCeWDQplbmRzdHJlYW0NZW5kb2JqDTI'
                                  'gMCBvYmoNPDwvTGVuZ3RoIDM1MjUvU3VidHlwZS9YTUwvVHlwZS9NZXRhZGF0YT4+c3RyZWFtDQo8P3hwYWN'
                                  'rZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/Pgo8eDp4bXBtZXRhIHhtbG5'
                                  'zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjQtYzAwNSA3OC4xNDczMjY'
                                  'sIDIwMTIvMDgvMjMtMTM6MDM6MDMgICAgICAgICI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d'
                                  '3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmR'
                                  'mOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnBkZj0iaHR0cDovL25zLmFkb2JlLmNvbS9wZGYvMS4zLyI'
                                  'KICAgICAgICAgICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICA'
                                  'gICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIKICAgICAgICAgICAgeG1'
                                  'sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIj4KICAgICAgICAgPHBkZjpQcm9kdWN'
                                  'lcj5BY3JvYmF0IERpc3RpbGxlciA2LjAgKFdpbmRvd3MpPC9wZGY6UHJvZHVjZXI+CiAgICAgICAgIDx4bXA'
                                  '6Q3JlYXRlRGF0ZT4yMDA2LTAzLTA2VDE1OjA2OjMzLTA1OjAwPC94bXA6Q3JlYXRlRGF0ZT4KICAgICAgICA'
                                  'gPHhtcDpDcmVhdG9yVG9vbD5BZG9iZVBTNS5kbGwgVmVyc2lvbiA1LjIuMjwveG1wOkNyZWF0b3JUb29sPgo'
                                  'gICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAxNi0wNy0xNVQxMDoxMjoyMSswODowMDwveG1wOk1vZGlmeUR'
                                  'hdGU+CiAgICAgICAgIDx4bXA6TWV0YWRhdGFEYXRlPjIwMTYtMDctMTVUMTA6MTI6MjErMDg6MDA8L3htcDp'
                                  'NZXRhZGF0YURhdGU+CiAgICAgICAgIDx4bXBNTTpEb2N1bWVudElEPnV1aWQ6ZmYzZGNmZDEtMjNmYS00NzZ'
                                  'mLTgzOWEtM2U1Y2FlMmRhMmViPC94bXBNTTpEb2N1bWVudElEPgogICAgICAgICA8eG1wTU06SW5zdGFuY2V'
                                  'JRD51dWlkOjM1OTM1MGIzLWFmNDAtNGQ4YS05ZDZjLTAzMTg2YjRmZmIzNjwveG1wTU06SW5zdGFuY2VJRD4'
                                  'KICAgICAgICAgPGRjOmZvcm1hdD5hcHBsaWNhdGlvbi9wZGY8L2RjOmZvcm1hdD4KICAgICAgICAgPGRjOnR'
                                  'pdGxlPgogICAgICAgICAgICA8cmRmOkFsdD4KICAgICAgICAgICAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1'
                                  'kZWZhdWx0Ij5CbGFuayBQREYgRG9jdW1lbnQ8L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6QWx0PgogICA'
                                  'gICAgICA8L2RjOnRpdGxlPgogICAgICAgICA8ZGM6Y3JlYXRvcj4KICAgICAgICAgICAgPHJkZjpTZXE+CiA'
                                  'gICAgICAgICAgICAgIDxyZGY6bGk+RGVwYXJ0bWVudCBvZiBKdXN0aWNlIChFeGVjdXRpdmUgT2ZmaWNlIG9'
                                  'mIEltbWlncmF0aW9uIFJldmlldyk8L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6U2VxPgogICAgICAgIC'
                                  'A8L2RjOmNyZWF0b3I+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZX'
                                  'RhPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC'
                                  'AgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9InciPz4NCmVuZHN0cm'
                                  'VhbQ1lbmRvYmoNMTEgMCBvYmoNPDwvTWV0YWRhdGEgMiAwIFIvUGFnZUxhYmVscyA2IDAgUi9QYWdlcyA4ID'
                                  'AgUi9UeXBlL0NhdGFsb2c+Pg1lbmRvYmoNMjMgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aC'
                                  'AxMD4+c3RyZWFtDQpIiQIIMAAAAAABDQplbmRzdHJlYW0NZW5kb2JqDTI4IDAgb2JqDTw8L0RlY29kZVBhcm'
                                  '1zPDwvQ29sdW1ucyA0L1ByZWRpY3RvciAxMj4+L0ZpbHRlci9GbGF0ZURlY29kZS9JRFs8REI3Nzc1Q0NFMj'
                                  'I3RjZCMzBDNDQwREY0MjIxREMzOTA+PEJGQ0NDRjNGNTdGNjEzNEFCRDNDMDRBOUU0Q0ExMDZFPl0vSW5mby'
                                  'A5IDAgUi9MZW5ndGggODAvUm9vdCAxMSAwIFIvU2l6ZSAyOS9UeXBlL1hSZWYvV1sxIDIgMV0+PnN0cmVhbQ'
                                  '0KaN5iYgACJjDByGzIwPT/73koF0wwMUiBWYxA4v9/EMHA9I/hBVCxoDOQeH8DxH2KrIMIglFwIpD1vh5IMJ'
                                  'qBxPpArHYgwd/KABBgAP8bEC0NCmVuZHN0cmVhbQ1lbmRvYmoNc3RhcnR4cmVmDQo0NTc2DQolJUVPRg0K')
                      ),
            PdfReport(REPORTNUMBER='A0000002',
                      PDF_ID=123457,
                      PDFREPORT1='#$%$#^%$^$%FDGSFGSDGFDSG====================='),
        ])
        session.commit()
    return conn_str
