name: Towing post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Lint with pylint
        run: |
          pip install -U pylint -r requirements.txt
          pylint trafficstat
      - name: Lint with flake8
        run : |
          pip install -U flake8 -r requirements.txt
          flake8 --config=.flake8 trafficstat
      - name: Look for security issues with Bandit
        run: |
          pip install -U bandit -r requirements.txt
          bandit trafficstat
