name: Trafficstat post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout bcgeocoder repo
        uses: actions/checkout@v2
        with:
          repository: city-of-baltimore/Geocoder
          ref: mypy
          path: geocoder-repo
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel pylint flake8 bandit mypy wheel
          pip install --upgrade ./geocoder-repo
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint src main.py
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 src main.py
      - name: Look for security issues with Bandit
        run: |
          bandit src main.py
      - name: Type checking
        run: |
          mypy src main.py
