name: Trafficstat post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install krb5
        run: |
          sudo apt-get update --fix-missing
          sudo apt install -y libxml2-utils libkrb5-dev
      - name: Tox
        run: |
          pip install tox
          tox
